#logging:
#  level:
#    com.zaxxer.hikari.HikariConfig: DEBUG
logging:
  level:
    org.springframework.jdbc: DEBUG
spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: bookaccount